[tool.poetry]
name = "crusher"
version = "0.1.3"
description = "Crush a deeply nested JSON string."
authors = ["rednafi <redowan.nafi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^10.3.0"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^6.2.4"
tox = "^3.23.1"
pip-tools = "^6.1.0"
pytest-cov = "^2.12.1"
isort = "^5.8.0"
mypy = "^0.902"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# CLI entrypoints
[tool.poetry.scripts]
crusher = "crusher:crusher.cli_entrypoint"


# Linter configuruation.
[tool.isort]
profile = "black"
atomic = true
extend_skip_glob = "migrations,scripts"
line_length = 88


[tool.black]
extend-exclude = "migrations,scripts"


[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
warn_no_return = false
warn_unused_ignores = true
allow_untyped_globals = true
allow_redefinition = true
pretty = true


[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true
